package Modelo.Validadores;

public enum ValidacionesContrasenia {
  CONTRASENIA_VACIA,
  TIENE_CARACTERES_UNICODE,
  CONTRASENIA_EN_TOP_10000,
  SIN_LETRA_MINUSCULA,
  SIN_LETRA_MAYUSCULA,
  SIN_NUMERO,
  NO_CUMPLE_LONGITUD,
  NUMEROS_CONSECUTIVOS,
  CARACTERES_SEGUIDOS_REPETIDOS,
  CARACTERES_CONSECUTIVOS

}
