@startuml
'https://plantuml.com/class-diagram


class Localizacion{
    TipoLocalizacion tipo
    String nombre
    int latitud
    int longitud
}
enum TipoLocalizacion{
    PROVINCIA
    MUNICIPIO
    DEPARTAMENTO
}

package "Responsables Servicios"{

    class Empresa{
        Usuario usuario
        List<LineaDeTransporte> serviciosPublicos
        Usuario usuarioDesignado

    }

    class OrganismoDeControl{
        Usuario usuario
        List<Servicio> servicios
        Usuario usuarioDesignado
    }

}
package "Servicios Publicos"{
class LineaDeTransporte{
    String nombre;
    Estacion origen
    Estacion destino
    List<Estacion> estaciones
    MedioDeTransporte medioTransporte
}
Enum MedioDeTransporte{
    SUBTERRANEO
    FERROCARRIL
}



class Estacion{
    String nombre
    Ubicacion ubicacion
    List<Servicio> servicios
}
}

package "Servicios"{
class Servicio{
    String descripcion
    List<Servicio> subServicios
}

class MedioElevacion{
    PuntoElevacion origen
    PuntoElevacion destino
}

Enum PuntoElevacion {
    CALLE
    ANDEN
    BARRERA
}
}

package "Comunidades"{
class Comunidad{
    List <Miembro> miembros
    List <Usuario> administradores
    List <Servicio> serviciosDeInteres
}
class Miembro{
    String nombre
    String apellido
    String correo
    List<Comunidad> comunidades
}

class Usuario{
     String nombre
     String contraseña    

}
}

LineaDeTransporte -->"*" Estacion
LineaDeTransporte --> MedioDeTransporte
LineaDeTransporte --> Localizacion

Servicio <|-- MedioElevacion

MedioElevacion --> PuntoElevacion
MedioElevacion --> PuntoElevacion

Estacion --> Localizacion
Estacion -->"*" Servicio

Comunidad -->"*" Miembro
Comunidad -->"*" Usuario
Comunidad -->"*" Servicio

Miembro -->"*" Comunidad
Miembro -->"*" Servicio

Empresa --> Usuario
Empresa -->"*" LineaDeTransporte

OrganismoDeControl --> Usuario
OrganismoDeControl -->"*" LineaDeTransporte

Usuario --> Localizacion

Localizacion --> TipoLocalizacion

@endum